version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "5001:5003"
    restart: always

  miniapp:
    build:
      context: ./miniapp
      dockerfile: Dockerfile.miniapp
    restart: always

  bot:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.bot
    restart: always

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - miniapp
      - api
    restart: always
