version: "3.9"

services:
  bot:
    build: .
    container_name: imegatron-bot
    command: python bot.py
    volumes:
      - ./subs.json:/app/subs.json
      - ./logs.txt:/app/logs.txt
    restart: always
    environment:
      - PYTHONUNBUFFERED=1

  api:
    build: ./api
    container_name: imegatron-api
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - ./subs.json:/app/subs.json
      - ./logs.txt:/app/logs.txt
    restart: always
    environment:
      - PYTHONUNBUFFERED=1

  miniapp:
    build: ./miniapp
    container_name: imegatron-miniapp
    ports:
      - "3000:3000"
    restart: always
