version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
    volumes:
      - ./subs.json:/app/subs.json
      - ./logs.txt:/app/logs.txt
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "5001:5000"
    restart: always

  miniapp:
    build:
      context: ./miniapp
      dockerfile: Dockerfile.miniapp
    ports:
      - "3000:80"
    restart: always
