version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
    container_name: imegatron-bot
    restart: always
    volumes:
      - ./config.json:/app/config.json
      - ./subs.json:/app/subs.json
      - ./logs.txt:/app/logs.txt
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: imegatron-api
    restart: always
    ports:
      - "5000:5000"

  miniapp:
    build:
      context: ./miniapp
      dockerfile: Dockerfile.miniapp
    container_name: imegatron-miniapp
    restart: always
    ports:
      - "3000:3000"
